// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agents.sql

package queries

import (
	"context"
	"database/sql"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (
    id, name, type, version,
    executable_hash, executable_path, pid, parent_pid, os_user,
    device_id, workspace_id, started_at, session_key_hash, session_expires_at,
    trust_level, status, last_seen_at, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, type, version,
    executable_hash, executable_path, pid, parent_pid, os_user,
    device_id, workspace_id, started_at, session_key_hash, session_expires_at,
    trust_level, status, last_seen_at, created_at, updated_at
`

type CreateAgentParams struct {
	ID               string
	Name             string
	Type             string
	Version          sql.NullString
	ExecutableHash   string
	ExecutablePath   string
	Pid              int64
	ParentPid        int64
	OsUser           string
	DeviceID         string
	WorkspaceID      string
	StartedAt        string
	SessionKeyHash   string
	SessionExpiresAt string
	TrustLevel       string
	Status           string
	LastSeenAt       string
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgent,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Version,
		arg.ExecutableHash,
		arg.ExecutablePath,
		arg.Pid,
		arg.ParentPid,
		arg.OsUser,
		arg.DeviceID,
		arg.WorkspaceID,
		arg.StartedAt,
		arg.SessionKeyHash,
		arg.SessionExpiresAt,
		arg.TrustLevel,
		arg.Status,
		arg.LastSeenAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Version,
		&i.ExecutableHash,
		&i.ExecutablePath,
		&i.Pid,
		&i.ParentPid,
		&i.OsUser,
		&i.DeviceID,
		&i.WorkspaceID,
		&i.StartedAt,
		&i.SessionKeyHash,
		&i.SessionExpiresAt,
		&i.TrustLevel,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentByBinding = `-- name: GetAgentByBinding :one
SELECT id, name, type, version,
    executable_hash, executable_path, pid, parent_pid, os_user,
    device_id, workspace_id, started_at, session_key_hash, session_expires_at,
    trust_level, status, last_seen_at, created_at, updated_at
FROM agents
WHERE device_id = ?
    AND workspace_id = ?
    AND executable_path = ?
    AND os_user = ?
    AND executable_hash = ?
ORDER BY id DESC
LIMIT 1
`

type GetAgentByBindingParams struct {
	DeviceID       string
	WorkspaceID    string
	ExecutablePath string
	OsUser         string
	ExecutableHash string
}

func (q *Queries) GetAgentByBinding(ctx context.Context, arg GetAgentByBindingParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByBinding,
		arg.DeviceID,
		arg.WorkspaceID,
		arg.ExecutablePath,
		arg.OsUser,
		arg.ExecutableHash,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Version,
		&i.ExecutableHash,
		&i.ExecutablePath,
		&i.Pid,
		&i.ParentPid,
		&i.OsUser,
		&i.DeviceID,
		&i.WorkspaceID,
		&i.StartedAt,
		&i.SessionKeyHash,
		&i.SessionExpiresAt,
		&i.TrustLevel,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, name, type, version,
    executable_hash, executable_path, pid, parent_pid, os_user,
    device_id, workspace_id, started_at, session_key_hash, session_expires_at,
    trust_level, status, last_seen_at, created_at, updated_at
FROM agents
WHERE id = ?
`

func (q *Queries) GetAgentByID(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Version,
		&i.ExecutableHash,
		&i.ExecutablePath,
		&i.Pid,
		&i.ParentPid,
		&i.OsUser,
		&i.DeviceID,
		&i.WorkspaceID,
		&i.StartedAt,
		&i.SessionKeyHash,
		&i.SessionExpiresAt,
		&i.TrustLevel,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentBySessionKeyHash = `-- name: GetAgentBySessionKeyHash :one
SELECT id, name, type, version,
    executable_hash, executable_path, pid, parent_pid, os_user,
    device_id, workspace_id, started_at, session_key_hash, session_expires_at,
    trust_level, status, last_seen_at, created_at, updated_at
FROM agents
WHERE session_key_hash = ?
`

func (q *Queries) GetAgentBySessionKeyHash(ctx context.Context, sessionKeyHash string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentBySessionKeyHash, sessionKeyHash)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Version,
		&i.ExecutableHash,
		&i.ExecutablePath,
		&i.Pid,
		&i.ParentPid,
		&i.OsUser,
		&i.DeviceID,
		&i.WorkspaceID,
		&i.StartedAt,
		&i.SessionKeyHash,
		&i.SessionExpiresAt,
		&i.TrustLevel,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, type, version,
    executable_hash, executable_path, pid, parent_pid, os_user,
    device_id, workspace_id, started_at, session_key_hash, session_expires_at,
    trust_level, status, last_seen_at, created_at, updated_at
FROM agents
ORDER BY last_seen_at DESC, id DESC
LIMIT ?
`

// Serves the Identities page's Agents column (design doc section 05).
// Newest first: the agent that just connected is the one the user is looking for.
func (q *Queries) ListAgents(ctx context.Context, limit int64) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Version,
			&i.ExecutableHash,
			&i.ExecutablePath,
			&i.Pid,
			&i.ParentPid,
			&i.OsUser,
			&i.DeviceID,
			&i.WorkspaceID,
			&i.StartedAt,
			&i.SessionKeyHash,
			&i.SessionExpiresAt,
			&i.TrustLevel,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebindAgent = `-- name: RebindAgent :one
UPDATE agents
SET pid = ?, parent_pid = ?, started_at = ?,
    session_key_hash = ?, session_expires_at = ?,
    status = 'active', last_seen_at = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, type, version,
    executable_hash, executable_path, pid, parent_pid, os_user,
    device_id, workspace_id, started_at, session_key_hash, session_expires_at,
    trust_level, status, last_seen_at, created_at, updated_at
`

type RebindAgentParams struct {
	Pid              int64
	ParentPid        int64
	StartedAt        string
	SessionKeyHash   string
	SessionExpiresAt string
	LastSeenAt       string
	UpdatedAt        string
	ID               string
}

func (q *Queries) RebindAgent(ctx context.Context, arg RebindAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, rebindAgent,
		arg.Pid,
		arg.ParentPid,
		arg.StartedAt,
		arg.SessionKeyHash,
		arg.SessionExpiresAt,
		arg.LastSeenAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Version,
		&i.ExecutableHash,
		&i.ExecutablePath,
		&i.Pid,
		&i.ParentPid,
		&i.OsUser,
		&i.DeviceID,
		&i.WorkspaceID,
		&i.StartedAt,
		&i.SessionKeyHash,
		&i.SessionExpiresAt,
		&i.TrustLevel,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentLastSeen = `-- name: UpdateAgentLastSeen :one
UPDATE agents
SET last_seen_at = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, type, version,
    executable_hash, executable_path, pid, parent_pid, os_user,
    device_id, workspace_id, started_at, session_key_hash, session_expires_at,
    trust_level, status, last_seen_at, created_at, updated_at
`

type UpdateAgentLastSeenParams struct {
	LastSeenAt string
	UpdatedAt  string
	ID         string
}

func (q *Queries) UpdateAgentLastSeen(ctx context.Context, arg UpdateAgentLastSeenParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, updateAgentLastSeen, arg.LastSeenAt, arg.UpdatedAt, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Version,
		&i.ExecutableHash,
		&i.ExecutablePath,
		&i.Pid,
		&i.ParentPid,
		&i.OsUser,
		&i.DeviceID,
		&i.WorkspaceID,
		&i.StartedAt,
		&i.SessionKeyHash,
		&i.SessionExpiresAt,
		&i.TrustLevel,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentStatus = `-- name: UpdateAgentStatus :one
UPDATE agents
SET status = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, type, version,
    executable_hash, executable_path, pid, parent_pid, os_user,
    device_id, workspace_id, started_at, session_key_hash, session_expires_at,
    trust_level, status, last_seen_at, created_at, updated_at
`

type UpdateAgentStatusParams struct {
	Status    string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, updateAgentStatus, arg.Status, arg.UpdatedAt, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Version,
		&i.ExecutableHash,
		&i.ExecutablePath,
		&i.Pid,
		&i.ParentPid,
		&i.OsUser,
		&i.DeviceID,
		&i.WorkspaceID,
		&i.StartedAt,
		&i.SessionKeyHash,
		&i.SessionExpiresAt,
		&i.TrustLevel,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentTrustLevel = `-- name: UpdateAgentTrustLevel :one
UPDATE agents
SET trust_level = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, type, version,
    executable_hash, executable_path, pid, parent_pid, os_user,
    device_id, workspace_id, started_at, session_key_hash, session_expires_at,
    trust_level, status, last_seen_at, created_at, updated_at
`

type UpdateAgentTrustLevelParams struct {
	TrustLevel string
	UpdatedAt  string
	ID         string
}

func (q *Queries) UpdateAgentTrustLevel(ctx context.Context, arg UpdateAgentTrustLevelParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, updateAgentTrustLevel, arg.TrustLevel, arg.UpdatedAt, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Version,
		&i.ExecutableHash,
		&i.ExecutablePath,
		&i.Pid,
		&i.ParentPid,
		&i.OsUser,
		&i.DeviceID,
		&i.WorkspaceID,
		&i.StartedAt,
		&i.SessionKeyHash,
		&i.SessionExpiresAt,
		&i.TrustLevel,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
