// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: approvals.sql

package queries

import (
	"context"
	"database/sql"
)

const createApproval = `-- name: CreateApproval :one
INSERT INTO approvals (
    id, decision_id, action, status, expires_at, decided_at, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, decision_id, action, status, expires_at, decided_at, created_at, updated_at
`

type CreateApprovalParams struct {
	ID         string
	DecisionID string
	Action     sql.NullString
	Status     string
	ExpiresAt  string
	DecidedAt  sql.NullString
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) (Approval, error) {
	row := q.db.QueryRowContext(ctx, createApproval,
		arg.ID,
		arg.DecisionID,
		arg.Action,
		arg.Status,
		arg.ExpiresAt,
		arg.DecidedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.Action,
		&i.Status,
		&i.ExpiresAt,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApprovalByDecisionID = `-- name: GetApprovalByDecisionID :one
SELECT id, decision_id, action, status, expires_at, decided_at, created_at, updated_at
FROM approvals
WHERE decision_id = ?
`

func (q *Queries) GetApprovalByDecisionID(ctx context.Context, decisionID string) (Approval, error) {
	row := q.db.QueryRowContext(ctx, getApprovalByDecisionID, decisionID)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.Action,
		&i.Status,
		&i.ExpiresAt,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApprovalByID = `-- name: GetApprovalByID :one
SELECT id, decision_id, action, status, expires_at, decided_at, created_at, updated_at
FROM approvals
WHERE id = ?
`

func (q *Queries) GetApprovalByID(ctx context.Context, id string) (Approval, error) {
	row := q.db.QueryRowContext(ctx, getApprovalByID, id)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.Action,
		&i.Status,
		&i.ExpiresAt,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApprovalsByStatus = `-- name: ListApprovalsByStatus :many
SELECT id, decision_id, action, status, expires_at, decided_at, created_at, updated_at
FROM approvals
WHERE status = ?
ORDER BY expires_at
LIMIT ?
`

type ListApprovalsByStatusParams struct {
	Status string
	Limit  int64
}

func (q *Queries) ListApprovalsByStatus(ctx context.Context, arg ListApprovalsByStatusParams) ([]Approval, error) {
	rows, err := q.db.QueryContext(ctx, listApprovalsByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Approval{}
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.DecisionID,
			&i.Action,
			&i.Status,
			&i.ExpiresAt,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApprovalsDueBefore = `-- name: ListPendingApprovalsDueBefore :many
SELECT id, decision_id, action, status, expires_at, decided_at, created_at, updated_at
FROM approvals
WHERE status = 'pending' AND expires_at <= ?
ORDER BY expires_at
LIMIT ?
`

type ListPendingApprovalsDueBeforeParams struct {
	ExpiresAt string
	Limit     int64
}

func (q *Queries) ListPendingApprovalsDueBefore(ctx context.Context, arg ListPendingApprovalsDueBeforeParams) ([]Approval, error) {
	rows, err := q.db.QueryContext(ctx, listPendingApprovalsDueBefore, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Approval{}
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.DecisionID,
			&i.Action,
			&i.Status,
			&i.ExpiresAt,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settleApproval = `-- name: SettleApproval :one
UPDATE approvals
SET action = ?, status = ?, decided_at = ?, updated_at = ?
WHERE id = ? AND status = 'pending'
RETURNING id, decision_id, action, status, expires_at, decided_at, created_at, updated_at
`

type SettleApprovalParams struct {
	Action    sql.NullString
	Status    string
	DecidedAt sql.NullString
	UpdatedAt string
	ID        string
}

func (q *Queries) SettleApproval(ctx context.Context, arg SettleApprovalParams) (Approval, error) {
	row := q.db.QueryRowContext(ctx, settleApproval,
		arg.Action,
		arg.Status,
		arg.DecidedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.Action,
		&i.Status,
		&i.ExpiresAt,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
