// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit_events.sql

package queries

import (
	"context"
	"database/sql"
)

const appendAuditEvent = `-- name: AppendAuditEvent :one
INSERT INTO audit_events (
    id, operation_id, event_type, agent_id, device_id, workspace_id,
    identity_id, credential_provider_id, service, operation, resource,
    resolved_scope, verdict, risk_level, decision_id, approval_id,
    lease_id, lease_status, outcome, response_status, duration_ms,
    is_redacted, metadata, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, operation_id, event_type, agent_id, device_id, workspace_id,
    identity_id, credential_provider_id, service, operation, resource,
    resolved_scope, verdict, risk_level, decision_id, approval_id,
    lease_id, lease_status, outcome, response_status, duration_ms,
    is_redacted, metadata, created_at
`

type AppendAuditEventParams struct {
	ID                   string
	OperationID          string
	EventType            string
	AgentID              sql.NullString
	DeviceID             sql.NullString
	WorkspaceID          sql.NullString
	IdentityID           sql.NullString
	CredentialProviderID sql.NullString
	Service              string
	Operation            string
	Resource             string
	ResolvedScope        string
	Verdict              sql.NullString
	RiskLevel            sql.NullString
	DecisionID           sql.NullString
	ApprovalID           sql.NullString
	LeaseID              sql.NullString
	LeaseStatus          sql.NullString
	Outcome              string
	ResponseStatus       sql.NullInt64
	DurationMs           int64
	IsRedacted           int64
	Metadata             string
	CreatedAt            string
}

func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRowContext(ctx, appendAuditEvent,
		arg.ID,
		arg.OperationID,
		arg.EventType,
		arg.AgentID,
		arg.DeviceID,
		arg.WorkspaceID,
		arg.IdentityID,
		arg.CredentialProviderID,
		arg.Service,
		arg.Operation,
		arg.Resource,
		arg.ResolvedScope,
		arg.Verdict,
		arg.RiskLevel,
		arg.DecisionID,
		arg.ApprovalID,
		arg.LeaseID,
		arg.LeaseStatus,
		arg.Outcome,
		arg.ResponseStatus,
		arg.DurationMs,
		arg.IsRedacted,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.EventType,
		&i.AgentID,
		&i.DeviceID,
		&i.WorkspaceID,
		&i.IdentityID,
		&i.CredentialProviderID,
		&i.Service,
		&i.Operation,
		&i.Resource,
		&i.ResolvedScope,
		&i.Verdict,
		&i.RiskLevel,
		&i.DecisionID,
		&i.ApprovalID,
		&i.LeaseID,
		&i.LeaseStatus,
		&i.Outcome,
		&i.ResponseStatus,
		&i.DurationMs,
		&i.IsRedacted,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const countAuditEventsBefore = `-- name: CountAuditEventsBefore :one
SELECT count(*) FROM audit_events
WHERE created_at < ?
`

func (q *Queries) CountAuditEventsBefore(ctx context.Context, createdAt string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditEventsBefore, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAuditEventByID = `-- name: GetAuditEventByID :one
SELECT id, operation_id, event_type, agent_id, device_id, workspace_id,
    identity_id, credential_provider_id, service, operation, resource,
    resolved_scope, verdict, risk_level, decision_id, approval_id,
    lease_id, lease_status, outcome, response_status, duration_ms,
    is_redacted, metadata, created_at
FROM audit_events
WHERE id = ?
`

func (q *Queries) GetAuditEventByID(ctx context.Context, id string) (AuditEvent, error) {
	row := q.db.QueryRowContext(ctx, getAuditEventByID, id)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.EventType,
		&i.AgentID,
		&i.DeviceID,
		&i.WorkspaceID,
		&i.IdentityID,
		&i.CredentialProviderID,
		&i.Service,
		&i.Operation,
		&i.Resource,
		&i.ResolvedScope,
		&i.Verdict,
		&i.RiskLevel,
		&i.DecisionID,
		&i.ApprovalID,
		&i.LeaseID,
		&i.LeaseStatus,
		&i.Outcome,
		&i.ResponseStatus,
		&i.DurationMs,
		&i.IsRedacted,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, operation_id, event_type, agent_id, device_id, workspace_id,
    identity_id, credential_provider_id, service, operation, resource,
    resolved_scope, verdict, risk_level, decision_id, approval_id,
    lease_id, lease_status, outcome, response_status, duration_ms,
    is_redacted, metadata, created_at
FROM audit_events
WHERE created_at < ?
ORDER BY created_at DESC
LIMIT ?
`

type ListAuditEventsParams struct {
	CreatedAt string
	Limit     int64
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEvents, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.EventType,
			&i.AgentID,
			&i.DeviceID,
			&i.WorkspaceID,
			&i.IdentityID,
			&i.CredentialProviderID,
			&i.Service,
			&i.Operation,
			&i.Resource,
			&i.ResolvedScope,
			&i.Verdict,
			&i.RiskLevel,
			&i.DecisionID,
			&i.ApprovalID,
			&i.LeaseID,
			&i.LeaseStatus,
			&i.Outcome,
			&i.ResponseStatus,
			&i.DurationMs,
			&i.IsRedacted,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByAgent = `-- name: ListAuditEventsByAgent :many
SELECT id, operation_id, event_type, agent_id, device_id, workspace_id,
    identity_id, credential_provider_id, service, operation, resource,
    resolved_scope, verdict, risk_level, decision_id, approval_id,
    lease_id, lease_status, outcome, response_status, duration_ms,
    is_redacted, metadata, created_at
FROM audit_events
WHERE agent_id = ? AND created_at < ?
ORDER BY created_at DESC
LIMIT ?
`

type ListAuditEventsByAgentParams struct {
	AgentID   sql.NullString
	CreatedAt string
	Limit     int64
}

func (q *Queries) ListAuditEventsByAgent(ctx context.Context, arg ListAuditEventsByAgentParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsByAgent, arg.AgentID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.EventType,
			&i.AgentID,
			&i.DeviceID,
			&i.WorkspaceID,
			&i.IdentityID,
			&i.CredentialProviderID,
			&i.Service,
			&i.Operation,
			&i.Resource,
			&i.ResolvedScope,
			&i.Verdict,
			&i.RiskLevel,
			&i.DecisionID,
			&i.ApprovalID,
			&i.LeaseID,
			&i.LeaseStatus,
			&i.Outcome,
			&i.ResponseStatus,
			&i.DurationMs,
			&i.IsRedacted,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByService = `-- name: ListAuditEventsByService :many
SELECT id, operation_id, event_type, agent_id, device_id, workspace_id,
    identity_id, credential_provider_id, service, operation, resource,
    resolved_scope, verdict, risk_level, decision_id, approval_id,
    lease_id, lease_status, outcome, response_status, duration_ms,
    is_redacted, metadata, created_at
FROM audit_events
WHERE service = ? AND created_at < ?
ORDER BY created_at DESC
LIMIT ?
`

type ListAuditEventsByServiceParams struct {
	Service   string
	CreatedAt string
	Limit     int64
}

func (q *Queries) ListAuditEventsByService(ctx context.Context, arg ListAuditEventsByServiceParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsByService, arg.Service, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.EventType,
			&i.AgentID,
			&i.DeviceID,
			&i.WorkspaceID,
			&i.IdentityID,
			&i.CredentialProviderID,
			&i.Service,
			&i.Operation,
			&i.Resource,
			&i.ResolvedScope,
			&i.Verdict,
			&i.RiskLevel,
			&i.DecisionID,
			&i.ApprovalID,
			&i.LeaseID,
			&i.LeaseStatus,
			&i.Outcome,
			&i.ResponseStatus,
			&i.DurationMs,
			&i.IsRedacted,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAuditEventsBefore = `-- name: PruneAuditEventsBefore :execrows
DELETE FROM audit_events
WHERE created_at < ?
`

func (q *Queries) PruneAuditEventsBefore(ctx context.Context, createdAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAuditEventsBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
