// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: capability_requests.sql

package queries

import (
	"context"
	"database/sql"
)

const createCapabilityRequest = `-- name: CreateCapabilityRequest :one
INSERT INTO capability_requests (
    id, operation_id, agent_id, workspace_id, service, operation,
    resource, desired_change, reason, status, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, operation_id, agent_id, workspace_id, service, operation,
    resource, desired_change, reason, status, created_at, updated_at, change_preview
`

type CreateCapabilityRequestParams struct {
	ID            string
	OperationID   string
	AgentID       string
	WorkspaceID   string
	Service       string
	Operation     string
	Resource      string
	DesiredChange sql.NullString
	Reason        string
	Status        string
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) CreateCapabilityRequest(ctx context.Context, arg CreateCapabilityRequestParams) (CapabilityRequest, error) {
	row := q.db.QueryRowContext(ctx, createCapabilityRequest,
		arg.ID,
		arg.OperationID,
		arg.AgentID,
		arg.WorkspaceID,
		arg.Service,
		arg.Operation,
		arg.Resource,
		arg.DesiredChange,
		arg.Reason,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CapabilityRequest
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.AgentID,
		&i.WorkspaceID,
		&i.Service,
		&i.Operation,
		&i.Resource,
		&i.DesiredChange,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChangePreview,
	)
	return i, err
}

const getCapabilityRequestByID = `-- name: GetCapabilityRequestByID :one
SELECT id, operation_id, agent_id, workspace_id, service, operation,
    resource, desired_change, reason, status, created_at, updated_at, change_preview
FROM capability_requests
WHERE id = ?
`

func (q *Queries) GetCapabilityRequestByID(ctx context.Context, id string) (CapabilityRequest, error) {
	row := q.db.QueryRowContext(ctx, getCapabilityRequestByID, id)
	var i CapabilityRequest
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.AgentID,
		&i.WorkspaceID,
		&i.Service,
		&i.Operation,
		&i.Resource,
		&i.DesiredChange,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChangePreview,
	)
	return i, err
}

const listCapabilityRequestsByStatus = `-- name: ListCapabilityRequestsByStatus :many
SELECT id, operation_id, agent_id, workspace_id, service, operation,
    resource, desired_change, reason, status, created_at, updated_at, change_preview
FROM capability_requests
WHERE status = ?
ORDER BY created_at
LIMIT ?
`

type ListCapabilityRequestsByStatusParams struct {
	Status string
	Limit  int64
}

func (q *Queries) ListCapabilityRequestsByStatus(ctx context.Context, arg ListCapabilityRequestsByStatusParams) ([]CapabilityRequest, error) {
	rows, err := q.db.QueryContext(ctx, listCapabilityRequestsByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CapabilityRequest{}
	for rows.Next() {
		var i CapabilityRequest
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.AgentID,
			&i.WorkspaceID,
			&i.Service,
			&i.Operation,
			&i.Resource,
			&i.DesiredChange,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChangePreview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCapabilityRequestChangePreview = `-- name: UpdateCapabilityRequestChangePreview :execrows
UPDATE capability_requests
SET change_preview = ?, updated_at = ?
WHERE id = ? AND status = ?
`

type UpdateCapabilityRequestChangePreviewParams struct {
	ChangePreview sql.NullString
	UpdatedAt     string
	ID            string
	Status        string
}

// The preview only lands on a request that is still waiting for a person. Once a
// request has a verdict, the old value shown in the folio is the one the decision
// was made against, and writing over it afterwards rewrites that evidence. The
// status lives in the WHERE clause rather than in a read-then-check, so a
// concurrent decision is not overwritten by this update.
func (q *Queries) UpdateCapabilityRequestChangePreview(ctx context.Context, arg UpdateCapabilityRequestChangePreviewParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCapabilityRequestChangePreview,
		arg.ChangePreview,
		arg.UpdatedAt,
		arg.ID,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCapabilityRequestStatus = `-- name: UpdateCapabilityRequestStatus :one
UPDATE capability_requests
SET status = ?, updated_at = ?
WHERE id = ? AND status = ?
RETURNING id, operation_id, agent_id, workspace_id, service, operation,
    resource, desired_change, reason, status, created_at, updated_at, change_preview
`

type UpdateCapabilityRequestStatusParams struct {
	Status    string
	UpdatedAt string
	ID        string
	Status_2  string
}

func (q *Queries) UpdateCapabilityRequestStatus(ctx context.Context, arg UpdateCapabilityRequestStatusParams) (CapabilityRequest, error) {
	row := q.db.QueryRowContext(ctx, updateCapabilityRequestStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.Status_2,
	)
	var i CapabilityRequest
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.AgentID,
		&i.WorkspaceID,
		&i.Service,
		&i.Operation,
		&i.Resource,
		&i.DesiredChange,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChangePreview,
	)
	return i, err
}
