// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: credential_references.sql

package queries

import (
	"context"
	"database/sql"
)

const createCredentialReference = `-- name: CreateCredentialReference :one
INSERT INTO credential_references (
    id, provider_id, provider_item_ref, field,
    service, account_label, metadata, capabilities,
    health_status, last_verified_at, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, provider_id, provider_item_ref, field,
    service, account_label, metadata, capabilities,
    health_status, last_verified_at, created_at, updated_at
`

type CreateCredentialReferenceParams struct {
	ID              string
	ProviderID      string
	ProviderItemRef string
	Field           string
	Service         string
	AccountLabel    string
	Metadata        string
	Capabilities    string
	HealthStatus    string
	LastVerifiedAt  sql.NullString
	CreatedAt       string
	UpdatedAt       string
}

func (q *Queries) CreateCredentialReference(ctx context.Context, arg CreateCredentialReferenceParams) (CredentialReference, error) {
	row := q.db.QueryRowContext(ctx, createCredentialReference,
		arg.ID,
		arg.ProviderID,
		arg.ProviderItemRef,
		arg.Field,
		arg.Service,
		arg.AccountLabel,
		arg.Metadata,
		arg.Capabilities,
		arg.HealthStatus,
		arg.LastVerifiedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CredentialReference
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderItemRef,
		&i.Field,
		&i.Service,
		&i.AccountLabel,
		&i.Metadata,
		&i.Capabilities,
		&i.HealthStatus,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialReferenceByID = `-- name: GetCredentialReferenceByID :one
SELECT id, provider_id, provider_item_ref, field,
    service, account_label, metadata, capabilities,
    health_status, last_verified_at, created_at, updated_at
FROM credential_references
WHERE id = ?
`

func (q *Queries) GetCredentialReferenceByID(ctx context.Context, id string) (CredentialReference, error) {
	row := q.db.QueryRowContext(ctx, getCredentialReferenceByID, id)
	var i CredentialReference
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderItemRef,
		&i.Field,
		&i.Service,
		&i.AccountLabel,
		&i.Metadata,
		&i.Capabilities,
		&i.HealthStatus,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCredentialReferenceHealth = `-- name: UpdateCredentialReferenceHealth :one
UPDATE credential_references
SET health_status = ?, last_verified_at = ?, updated_at = ?
WHERE id = ?
RETURNING id, provider_id, provider_item_ref, field,
    service, account_label, metadata, capabilities,
    health_status, last_verified_at, created_at, updated_at
`

type UpdateCredentialReferenceHealthParams struct {
	HealthStatus   string
	LastVerifiedAt sql.NullString
	UpdatedAt      string
	ID             string
}

func (q *Queries) UpdateCredentialReferenceHealth(ctx context.Context, arg UpdateCredentialReferenceHealthParams) (CredentialReference, error) {
	row := q.db.QueryRowContext(ctx, updateCredentialReferenceHealth,
		arg.HealthStatus,
		arg.LastVerifiedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i CredentialReference
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderItemRef,
		&i.Field,
		&i.Service,
		&i.AccountLabel,
		&i.Metadata,
		&i.Capabilities,
		&i.HealthStatus,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
