// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: credential_providers.sql

package queries

import (
	"context"
)

const createCredentialProvider = `-- name: CreateCredentialProvider :one
INSERT INTO credential_providers (id, kind, label, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, kind, label, created_at, updated_at
`

type CreateCredentialProviderParams struct {
	ID        string
	Kind      string
	Label     string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateCredentialProvider(ctx context.Context, arg CreateCredentialProviderParams) (CredentialProvider, error) {
	row := q.db.QueryRowContext(ctx, createCredentialProvider,
		arg.ID,
		arg.Kind,
		arg.Label,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CredentialProvider
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialProviderByID = `-- name: GetCredentialProviderByID :one
SELECT id, kind, label, created_at, updated_at
FROM credential_providers
WHERE id = ?
`

func (q *Queries) GetCredentialProviderByID(ctx context.Context, id string) (CredentialProvider, error) {
	row := q.db.QueryRowContext(ctx, getCredentialProviderByID, id)
	var i CredentialProvider
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialProviderByKindAndLabel = `-- name: GetCredentialProviderByKindAndLabel :one
SELECT id, kind, label, created_at, updated_at
FROM credential_providers
WHERE kind = ? AND label = ?
`

type GetCredentialProviderByKindAndLabelParams struct {
	Kind  string
	Label string
}

func (q *Queries) GetCredentialProviderByKindAndLabel(ctx context.Context, arg GetCredentialProviderByKindAndLabelParams) (CredentialProvider, error) {
	row := q.db.QueryRowContext(ctx, getCredentialProviderByKindAndLabel, arg.Kind, arg.Label)
	var i CredentialProvider
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
