// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: decisions.sql

package queries

import (
	"context"
	"database/sql"
)

const createDecision = `-- name: CreateDecision :one
INSERT INTO decisions (
    id, capability_request_id, verdict, risk_level, risk_factors,
    identity_id, match_level, resolved_scope, approval_requirement,
    reason_code, created_at, trust_memory_id
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, capability_request_id, verdict, risk_level, risk_factors,
    identity_id, match_level, resolved_scope, approval_requirement,
    reason_code, created_at, trust_memory_id
`

type CreateDecisionParams struct {
	ID                  string
	CapabilityRequestID string
	Verdict             string
	RiskLevel           string
	RiskFactors         string
	IdentityID          sql.NullString
	MatchLevel          sql.NullString
	ResolvedScope       string
	ApprovalRequirement string
	ReasonCode          string
	CreatedAt           string
	TrustMemoryID       sql.NullString
}

func (q *Queries) CreateDecision(ctx context.Context, arg CreateDecisionParams) (Decision, error) {
	row := q.db.QueryRowContext(ctx, createDecision,
		arg.ID,
		arg.CapabilityRequestID,
		arg.Verdict,
		arg.RiskLevel,
		arg.RiskFactors,
		arg.IdentityID,
		arg.MatchLevel,
		arg.ResolvedScope,
		arg.ApprovalRequirement,
		arg.ReasonCode,
		arg.CreatedAt,
		arg.TrustMemoryID,
	)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.CapabilityRequestID,
		&i.Verdict,
		&i.RiskLevel,
		&i.RiskFactors,
		&i.IdentityID,
		&i.MatchLevel,
		&i.ResolvedScope,
		&i.ApprovalRequirement,
		&i.ReasonCode,
		&i.CreatedAt,
		&i.TrustMemoryID,
	)
	return i, err
}

const getDecisionByCapabilityRequestID = `-- name: GetDecisionByCapabilityRequestID :one
SELECT id, capability_request_id, verdict, risk_level, risk_factors,
    identity_id, match_level, resolved_scope, approval_requirement,
    reason_code, created_at, trust_memory_id
FROM decisions
WHERE capability_request_id = ?
`

func (q *Queries) GetDecisionByCapabilityRequestID(ctx context.Context, capabilityRequestID string) (Decision, error) {
	row := q.db.QueryRowContext(ctx, getDecisionByCapabilityRequestID, capabilityRequestID)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.CapabilityRequestID,
		&i.Verdict,
		&i.RiskLevel,
		&i.RiskFactors,
		&i.IdentityID,
		&i.MatchLevel,
		&i.ResolvedScope,
		&i.ApprovalRequirement,
		&i.ReasonCode,
		&i.CreatedAt,
		&i.TrustMemoryID,
	)
	return i, err
}

const getDecisionByID = `-- name: GetDecisionByID :one
SELECT id, capability_request_id, verdict, risk_level, risk_factors,
    identity_id, match_level, resolved_scope, approval_requirement,
    reason_code, created_at, trust_memory_id
FROM decisions
WHERE id = ?
`

func (q *Queries) GetDecisionByID(ctx context.Context, id string) (Decision, error) {
	row := q.db.QueryRowContext(ctx, getDecisionByID, id)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.CapabilityRequestID,
		&i.Verdict,
		&i.RiskLevel,
		&i.RiskFactors,
		&i.IdentityID,
		&i.MatchLevel,
		&i.ResolvedScope,
		&i.ApprovalRequirement,
		&i.ReasonCode,
		&i.CreatedAt,
		&i.TrustMemoryID,
	)
	return i, err
}
