// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: devices.sql

package queries

import (
	"context"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id, fingerprint, name, trust_status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, fingerprint, name, trust_status, created_at, updated_at
`

type CreateDeviceParams struct {
	ID          string
	Fingerprint string
	Name        string
	TrustStatus string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice,
		arg.ID,
		arg.Fingerprint,
		arg.Name,
		arg.TrustStatus,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.Name,
		&i.TrustStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByFingerprint = `-- name: GetDeviceByFingerprint :one
SELECT id, fingerprint, name, trust_status, created_at, updated_at
FROM devices
WHERE fingerprint = ?
`

func (q *Queries) GetDeviceByFingerprint(ctx context.Context, fingerprint string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByFingerprint, fingerprint)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.Name,
		&i.TrustStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, fingerprint, name, trust_status, created_at, updated_at
FROM devices
WHERE id = ?
`

func (q *Queries) GetDeviceByID(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.Name,
		&i.TrustStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeviceTrustStatus = `-- name: UpdateDeviceTrustStatus :one
UPDATE devices
SET trust_status = ?, updated_at = ?
WHERE id = ?
RETURNING id, fingerprint, name, trust_status, created_at, updated_at
`

type UpdateDeviceTrustStatusParams struct {
	TrustStatus string
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateDeviceTrustStatus(ctx context.Context, arg UpdateDeviceTrustStatusParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, updateDeviceTrustStatus, arg.TrustStatus, arg.UpdatedAt, arg.ID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.Name,
		&i.TrustStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
