// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: identities.sql

package queries

import (
	"context"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO identities (
    id, service, account_label, environment, is_default,
    status, credential_reference_id, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, service, account_label, environment, is_default,
    status, credential_reference_id, created_at, updated_at
`

type CreateIdentityParams struct {
	ID                    string
	Service               string
	AccountLabel          string
	Environment           string
	IsDefault             int64
	Status                string
	CredentialReferenceID string
	CreatedAt             string
	UpdatedAt             string
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, createIdentity,
		arg.ID,
		arg.Service,
		arg.AccountLabel,
		arg.Environment,
		arg.IsDefault,
		arg.Status,
		arg.CredentialReferenceID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.AccountLabel,
		&i.Environment,
		&i.IsDefault,
		&i.Status,
		&i.CredentialReferenceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityByID = `-- name: GetIdentityByID :one
SELECT id, service, account_label, environment, is_default,
    status, credential_reference_id, created_at, updated_at
FROM identities
WHERE id = ?
`

func (q *Queries) GetIdentityByID(ctx context.Context, id string) (Identity, error) {
	row := q.db.QueryRowContext(ctx, getIdentityByID, id)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.AccountLabel,
		&i.Environment,
		&i.IsDefault,
		&i.Status,
		&i.CredentialReferenceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityByServiceAndAccountLabel = `-- name: GetIdentityByServiceAndAccountLabel :one
SELECT id, service, account_label, environment, is_default,
    status, credential_reference_id, created_at, updated_at
FROM identities
WHERE service = ? AND account_label = ?
`

type GetIdentityByServiceAndAccountLabelParams struct {
	Service      string
	AccountLabel string
}

func (q *Queries) GetIdentityByServiceAndAccountLabel(ctx context.Context, arg GetIdentityByServiceAndAccountLabelParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, getIdentityByServiceAndAccountLabel, arg.Service, arg.AccountLabel)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.AccountLabel,
		&i.Environment,
		&i.IsDefault,
		&i.Status,
		&i.CredentialReferenceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIdentities = `-- name: ListIdentities :many
SELECT id, service, account_label, environment, is_default,
    status, credential_reference_id, created_at, updated_at
FROM identities
ORDER BY service, account_label
LIMIT ?
`

// Serves the Identities page (REQ-UI-005). Ordered by (service, account_label)
// so it walks uq_identities_service_label instead of sorting a scan result.
func (q *Queries) ListIdentities(ctx context.Context, limit int64) ([]Identity, error) {
	rows, err := q.db.QueryContext(ctx, listIdentities, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Identity{}
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.AccountLabel,
			&i.Environment,
			&i.IsDefault,
			&i.Status,
			&i.CredentialReferenceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentitiesByService = `-- name: ListIdentitiesByService :many
SELECT id, service, account_label, environment, is_default,
    status, credential_reference_id, created_at, updated_at
FROM identities
WHERE service = ?
ORDER BY account_label
LIMIT ?
`

type ListIdentitiesByServiceParams struct {
	Service string
	Limit   int64
}

func (q *Queries) ListIdentitiesByService(ctx context.Context, arg ListIdentitiesByServiceParams) ([]Identity, error) {
	rows, err := q.db.QueryContext(ctx, listIdentitiesByService, arg.Service, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Identity{}
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.AccountLabel,
			&i.Environment,
			&i.IsDefault,
			&i.Status,
			&i.CredentialReferenceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIdentityDefault = `-- name: UpdateIdentityDefault :one
UPDATE identities
SET is_default = ?, updated_at = ?
WHERE id = ?
RETURNING id, service, account_label, environment, is_default,
    status, credential_reference_id, created_at, updated_at
`

type UpdateIdentityDefaultParams struct {
	IsDefault int64
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateIdentityDefault(ctx context.Context, arg UpdateIdentityDefaultParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, updateIdentityDefault, arg.IsDefault, arg.UpdatedAt, arg.ID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.AccountLabel,
		&i.Environment,
		&i.IsDefault,
		&i.Status,
		&i.CredentialReferenceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIdentityStatus = `-- name: UpdateIdentityStatus :one
UPDATE identities
SET status = ?, updated_at = ?
WHERE id = ?
RETURNING id, service, account_label, environment, is_default,
    status, credential_reference_id, created_at, updated_at
`

type UpdateIdentityStatusParams struct {
	Status    string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateIdentityStatus(ctx context.Context, arg UpdateIdentityStatusParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, updateIdentityStatus, arg.Status, arg.UpdatedAt, arg.ID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.AccountLabel,
		&i.Environment,
		&i.IsDefault,
		&i.Status,
		&i.CredentialReferenceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
