// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: leases.sql

package queries

import (
	"context"
	"database/sql"
)

const closeLease = `-- name: CloseLease :one
UPDATE leases
SET status = ?, updated_at = ?
WHERE id = ? AND status = 'active'
RETURNING id, agent_id, identity_id, service, resource_scope, capabilities,
    expires_at, request_limit, used_requests, status, approval_id,
    is_session_bound, created_at, updated_at, source_memory_id
`

type CloseLeaseParams struct {
	Status    string
	UpdatedAt string
	ID        string
}

func (q *Queries) CloseLease(ctx context.Context, arg CloseLeaseParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, closeLease, arg.Status, arg.UpdatedAt, arg.ID)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.IdentityID,
		&i.Service,
		&i.ResourceScope,
		&i.Capabilities,
		&i.ExpiresAt,
		&i.RequestLimit,
		&i.UsedRequests,
		&i.Status,
		&i.ApprovalID,
		&i.IsSessionBound,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceMemoryID,
	)
	return i, err
}

const consumeLease = `-- name: ConsumeLease :one
UPDATE leases
SET used_requests = used_requests + 1, updated_at = ?
WHERE id = ?
    AND status = 'active'
    AND expires_at > ?
    AND (request_limit IS NULL OR used_requests < request_limit)
RETURNING id, agent_id, identity_id, service, resource_scope, capabilities,
    expires_at, request_limit, used_requests, status, approval_id,
    is_session_bound, created_at, updated_at, source_memory_id
`

type ConsumeLeaseParams struct {
	UpdatedAt string
	ID        string
	ExpiresAt string
}

func (q *Queries) ConsumeLease(ctx context.Context, arg ConsumeLeaseParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, consumeLease, arg.UpdatedAt, arg.ID, arg.ExpiresAt)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.IdentityID,
		&i.Service,
		&i.ResourceScope,
		&i.Capabilities,
		&i.ExpiresAt,
		&i.RequestLimit,
		&i.UsedRequests,
		&i.Status,
		&i.ApprovalID,
		&i.IsSessionBound,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceMemoryID,
	)
	return i, err
}

const createLease = `-- name: CreateLease :one
INSERT INTO leases (
    id, agent_id, identity_id, service, resource_scope, capabilities,
    expires_at, request_limit, used_requests, status, approval_id,
    is_session_bound, created_at, updated_at, source_memory_id
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, agent_id, identity_id, service, resource_scope, capabilities,
    expires_at, request_limit, used_requests, status, approval_id,
    is_session_bound, created_at, updated_at, source_memory_id
`

type CreateLeaseParams struct {
	ID             string
	AgentID        string
	IdentityID     string
	Service        string
	ResourceScope  string
	Capabilities   string
	ExpiresAt      string
	RequestLimit   sql.NullInt64
	UsedRequests   int64
	Status         string
	ApprovalID     sql.NullString
	IsSessionBound int64
	CreatedAt      string
	UpdatedAt      string
	SourceMemoryID sql.NullString
}

func (q *Queries) CreateLease(ctx context.Context, arg CreateLeaseParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, createLease,
		arg.ID,
		arg.AgentID,
		arg.IdentityID,
		arg.Service,
		arg.ResourceScope,
		arg.Capabilities,
		arg.ExpiresAt,
		arg.RequestLimit,
		arg.UsedRequests,
		arg.Status,
		arg.ApprovalID,
		arg.IsSessionBound,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SourceMemoryID,
	)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.IdentityID,
		&i.Service,
		&i.ResourceScope,
		&i.Capabilities,
		&i.ExpiresAt,
		&i.RequestLimit,
		&i.UsedRequests,
		&i.Status,
		&i.ApprovalID,
		&i.IsSessionBound,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceMemoryID,
	)
	return i, err
}

const getLeaseByApprovalID = `-- name: GetLeaseByApprovalID :one
SELECT id, agent_id, identity_id, service, resource_scope, capabilities,
    expires_at, request_limit, used_requests, status, approval_id,
    is_session_bound, created_at, updated_at, source_memory_id
FROM leases
WHERE approval_id = ?
`

func (q *Queries) GetLeaseByApprovalID(ctx context.Context, approvalID sql.NullString) (Lease, error) {
	row := q.db.QueryRowContext(ctx, getLeaseByApprovalID, approvalID)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.IdentityID,
		&i.Service,
		&i.ResourceScope,
		&i.Capabilities,
		&i.ExpiresAt,
		&i.RequestLimit,
		&i.UsedRequests,
		&i.Status,
		&i.ApprovalID,
		&i.IsSessionBound,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceMemoryID,
	)
	return i, err
}

const getLeaseByID = `-- name: GetLeaseByID :one
SELECT id, agent_id, identity_id, service, resource_scope, capabilities,
    expires_at, request_limit, used_requests, status, approval_id,
    is_session_bound, created_at, updated_at, source_memory_id
FROM leases
WHERE id = ?
`

func (q *Queries) GetLeaseByID(ctx context.Context, id string) (Lease, error) {
	row := q.db.QueryRowContext(ctx, getLeaseByID, id)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.IdentityID,
		&i.Service,
		&i.ResourceScope,
		&i.Capabilities,
		&i.ExpiresAt,
		&i.RequestLimit,
		&i.UsedRequests,
		&i.Status,
		&i.ApprovalID,
		&i.IsSessionBound,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceMemoryID,
	)
	return i, err
}

const listActiveLeasesByCredentialReference = `-- name: ListActiveLeasesByCredentialReference :many
SELECT l.id, l.agent_id, l.identity_id, l.service, l.resource_scope, l.capabilities,
    l.expires_at, l.request_limit, l.used_requests, l.status, l.approval_id,
    l.is_session_bound, l.created_at, l.updated_at, l.source_memory_id
FROM leases AS l
JOIN identities AS i ON i.id = l.identity_id
WHERE l.status = 'active' AND i.credential_reference_id = ?
ORDER BY l.expires_at
LIMIT ?
`

type ListActiveLeasesByCredentialReferenceParams struct {
	CredentialReferenceID string
	Limit                 int64
}

// Serves the cascade revocation required when a credential is disconnected
// (REQ-CRED-005 AC3). Walks leases -> identities -> credential_references.
func (q *Queries) ListActiveLeasesByCredentialReference(ctx context.Context, arg ListActiveLeasesByCredentialReferenceParams) ([]Lease, error) {
	rows, err := q.db.QueryContext(ctx, listActiveLeasesByCredentialReference, arg.CredentialReferenceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lease{}
	for rows.Next() {
		var i Lease
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.IdentityID,
			&i.Service,
			&i.ResourceScope,
			&i.Capabilities,
			&i.ExpiresAt,
			&i.RequestLimit,
			&i.UsedRequests,
			&i.Status,
			&i.ApprovalID,
			&i.IsSessionBound,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceMemoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveLeasesByIdentity = `-- name: ListActiveLeasesByIdentity :many
SELECT id, agent_id, identity_id, service, resource_scope, capabilities,
    expires_at, request_limit, used_requests, status, approval_id,
    is_session_bound, created_at, updated_at, source_memory_id
FROM leases
WHERE identity_id = ? AND status = 'active'
ORDER BY expires_at
LIMIT ?
`

type ListActiveLeasesByIdentityParams struct {
	IdentityID string
	Limit      int64
}

// Feeds the cascade that revokes an identity's leases on disconnect
// (REQ-IDENT-001 AC2).
func (q *Queries) ListActiveLeasesByIdentity(ctx context.Context, arg ListActiveLeasesByIdentityParams) ([]Lease, error) {
	rows, err := q.db.QueryContext(ctx, listActiveLeasesByIdentity, arg.IdentityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lease{}
	for rows.Next() {
		var i Lease
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.IdentityID,
			&i.Service,
			&i.ResourceScope,
			&i.Capabilities,
			&i.ExpiresAt,
			&i.RequestLimit,
			&i.UsedRequests,
			&i.Status,
			&i.ApprovalID,
			&i.IsSessionBound,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceMemoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveLeasesDueBefore = `-- name: ListActiveLeasesDueBefore :many
SELECT id, agent_id, identity_id, service, resource_scope, capabilities,
    expires_at, request_limit, used_requests, status, approval_id,
    is_session_bound, created_at, updated_at, source_memory_id
FROM leases
WHERE status = 'active' AND expires_at <= ?
ORDER BY expires_at
LIMIT ?
`

type ListActiveLeasesDueBeforeParams struct {
	ExpiresAt string
	Limit     int64
}

func (q *Queries) ListActiveLeasesDueBefore(ctx context.Context, arg ListActiveLeasesDueBeforeParams) ([]Lease, error) {
	rows, err := q.db.QueryContext(ctx, listActiveLeasesDueBefore, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lease{}
	for rows.Next() {
		var i Lease
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.IdentityID,
			&i.Service,
			&i.ResourceScope,
			&i.Capabilities,
			&i.ExpiresAt,
			&i.RequestLimit,
			&i.UsedRequests,
			&i.Status,
			&i.ApprovalID,
			&i.IsSessionBound,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceMemoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSessionBoundLeasesByAgent = `-- name: ListActiveSessionBoundLeasesByAgent :many
SELECT id, agent_id, identity_id, service, resource_scope, capabilities,
    expires_at, request_limit, used_requests, status, approval_id,
    is_session_bound, created_at, updated_at, source_memory_id
FROM leases
WHERE agent_id = ? AND status = 'active' AND is_session_bound = 1
ORDER BY expires_at
LIMIT ?
`

type ListActiveSessionBoundLeasesByAgentParams struct {
	AgentID string
	Limit   int64
}

// Feeds the cascade that revokes an agent's task-scoped leases when its session
// ends (REQ-CLI-002 AC3). Only session-bound leases are listed: a lease granted
// for a single call or for the whole project outlives the process that asked
// for it, and revoking those here would silently shrink what the user allowed.
func (q *Queries) ListActiveSessionBoundLeasesByAgent(ctx context.Context, arg ListActiveSessionBoundLeasesByAgentParams) ([]Lease, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSessionBoundLeasesByAgent, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lease{}
	for rows.Next() {
		var i Lease
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.IdentityID,
			&i.Service,
			&i.ResourceScope,
			&i.Capabilities,
			&i.ExpiresAt,
			&i.RequestLimit,
			&i.UsedRequests,
			&i.Status,
			&i.ApprovalID,
			&i.IsSessionBound,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceMemoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeasesByStatus = `-- name: ListLeasesByStatus :many
SELECT id, agent_id, identity_id, service, resource_scope, capabilities,
    expires_at, request_limit, used_requests, status, approval_id,
    is_session_bound, created_at, updated_at, source_memory_id
FROM leases
WHERE status = ?
ORDER BY expires_at
LIMIT ?
`

type ListLeasesByStatusParams struct {
	Status string
	Limit  int64
}

func (q *Queries) ListLeasesByStatus(ctx context.Context, arg ListLeasesByStatusParams) ([]Lease, error) {
	rows, err := q.db.QueryContext(ctx, listLeasesByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lease{}
	for rows.Next() {
		var i Lease
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.IdentityID,
			&i.Service,
			&i.ResourceScope,
			&i.Capabilities,
			&i.ExpiresAt,
			&i.RequestLimit,
			&i.UsedRequests,
			&i.Status,
			&i.ApprovalID,
			&i.IsSessionBound,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceMemoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shortenLease = `-- name: ShortenLease :one
UPDATE leases
SET expires_at = ?, updated_at = ?
WHERE id = ? AND status = 'active' AND expires_at > ?
RETURNING id, agent_id, identity_id, service, resource_scope, capabilities,
    expires_at, request_limit, used_requests, status, approval_id,
    is_session_bound, created_at, updated_at, source_memory_id
`

type ShortenLeaseParams struct {
	ExpiresAt   string
	UpdatedAt   string
	ID          string
	ExpiresAt_2 string
}

func (q *Queries) ShortenLease(ctx context.Context, arg ShortenLeaseParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, shortenLease,
		arg.ExpiresAt,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpiresAt_2,
	)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.IdentityID,
		&i.Service,
		&i.ResourceScope,
		&i.Capabilities,
		&i.ExpiresAt,
		&i.RequestLimit,
		&i.UsedRequests,
		&i.Status,
		&i.ApprovalID,
		&i.IsSessionBound,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceMemoryID,
	)
	return i, err
}
