// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"database/sql"
)

type Agent struct {
	ID               string
	Name             string
	Type             string
	Version          sql.NullString
	ExecutableHash   string
	ExecutablePath   string
	Pid              int64
	ParentPid        int64
	OsUser           string
	DeviceID         string
	WorkspaceID      string
	StartedAt        string
	SessionKeyHash   string
	SessionExpiresAt string
	TrustLevel       string
	Status           string
	LastSeenAt       string
	CreatedAt        string
	UpdatedAt        string
}

type Approval struct {
	ID         string
	DecisionID string
	Action     sql.NullString
	Status     string
	ExpiresAt  string
	DecidedAt  sql.NullString
	CreatedAt  string
	UpdatedAt  string
}

type AuditEvent struct {
	ID                   string
	OperationID          string
	EventType            string
	AgentID              sql.NullString
	DeviceID             sql.NullString
	WorkspaceID          sql.NullString
	IdentityID           sql.NullString
	CredentialProviderID sql.NullString
	Service              string
	Operation            string
	Resource             string
	ResolvedScope        string
	Verdict              sql.NullString
	RiskLevel            sql.NullString
	DecisionID           sql.NullString
	ApprovalID           sql.NullString
	LeaseID              sql.NullString
	LeaseStatus          sql.NullString
	Outcome              string
	ResponseStatus       sql.NullInt64
	DurationMs           int64
	IsRedacted           int64
	Metadata             string
	CreatedAt            string
}

type CapabilityRequest struct {
	ID            string
	OperationID   string
	AgentID       string
	WorkspaceID   string
	Service       string
	Operation     string
	Resource      string
	DesiredChange sql.NullString
	Reason        string
	Status        string
	CreatedAt     string
	UpdatedAt     string
	ChangePreview sql.NullString
}

type CredentialProvider struct {
	ID        string
	Kind      string
	Label     string
	CreatedAt string
	UpdatedAt string
}

type CredentialReference struct {
	ID              string
	ProviderID      string
	ProviderItemRef string
	Field           string
	Service         string
	AccountLabel    string
	Metadata        string
	Capabilities    string
	HealthStatus    string
	LastVerifiedAt  sql.NullString
	CreatedAt       string
	UpdatedAt       string
}

type Decision struct {
	ID                  string
	CapabilityRequestID string
	Verdict             string
	RiskLevel           string
	RiskFactors         string
	IdentityID          sql.NullString
	MatchLevel          sql.NullString
	ResolvedScope       string
	ApprovalRequirement string
	ReasonCode          string
	CreatedAt           string
	TrustMemoryID       sql.NullString
}

type Device struct {
	ID          string
	Fingerprint string
	Name        string
	TrustStatus string
	CreatedAt   string
	UpdatedAt   string
}

type Identity struct {
	ID                    string
	Service               string
	AccountLabel          string
	Environment           string
	IsDefault             int64
	Status                string
	CredentialReferenceID string
	CreatedAt             string
	UpdatedAt             string
}

type Lease struct {
	ID             string
	AgentID        string
	IdentityID     string
	Service        string
	ResourceScope  string
	Capabilities   string
	ExpiresAt      string
	RequestLimit   sql.NullInt64
	UsedRequests   int64
	Status         string
	ApprovalID     sql.NullString
	IsSessionBound int64
	CreatedAt      string
	UpdatedAt      string
	SourceMemoryID sql.NullString
}

type ServiceAdapter struct {
	ID               string
	Service          string
	Kind             string
	DisplayName      string
	BaseUrl          string
	AuthScheme       string
	Capabilities     string
	AllowedPaths     string
	AllowedMethods   string
	RedactionRules   string
	DefaultRiskLevel string
	Status           string
	CreatedAt        string
	UpdatedAt        string
}

type Setting struct {
	ID        string
	Name      string
	Value     string
	CreatedAt string
	UpdatedAt string
}

type TrustMemory struct {
	ID                 string
	AgentID            string
	WorkspaceID        string
	IdentityID         string
	Service            string
	ResourceScope      string
	CapabilityScope    string
	Environment        string
	RiskCeiling        string
	ApprovalBehavior   string
	CreatedFrom        string
	Status             string
	InvalidationReason sql.NullString
	LastUsedAt         sql.NullString
	ExpiresAt          string
	CreatedAt          string
	UpdatedAt          string
}

type Workspace struct {
	ID                 string
	Path               string
	ProjectFingerprint string
	CreatedAt          string
	UpdatedAt          string
}
