// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: service_adapters.sql

package queries

import (
	"context"
)

const createServiceAdapter = `-- name: CreateServiceAdapter :one
INSERT INTO service_adapters (
    id, service, kind, display_name, base_url, auth_scheme,
    capabilities, allowed_paths, allowed_methods, redaction_rules,
    default_risk_level, status, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, service, kind, display_name, base_url, auth_scheme,
    capabilities, allowed_paths, allowed_methods, redaction_rules,
    default_risk_level, status, created_at, updated_at
`

type CreateServiceAdapterParams struct {
	ID               string
	Service          string
	Kind             string
	DisplayName      string
	BaseUrl          string
	AuthScheme       string
	Capabilities     string
	AllowedPaths     string
	AllowedMethods   string
	RedactionRules   string
	DefaultRiskLevel string
	Status           string
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) CreateServiceAdapter(ctx context.Context, arg CreateServiceAdapterParams) (ServiceAdapter, error) {
	row := q.db.QueryRowContext(ctx, createServiceAdapter,
		arg.ID,
		arg.Service,
		arg.Kind,
		arg.DisplayName,
		arg.BaseUrl,
		arg.AuthScheme,
		arg.Capabilities,
		arg.AllowedPaths,
		arg.AllowedMethods,
		arg.RedactionRules,
		arg.DefaultRiskLevel,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ServiceAdapter
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Kind,
		&i.DisplayName,
		&i.BaseUrl,
		&i.AuthScheme,
		&i.Capabilities,
		&i.AllowedPaths,
		&i.AllowedMethods,
		&i.RedactionRules,
		&i.DefaultRiskLevel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceAdapterByID = `-- name: GetServiceAdapterByID :one
SELECT id, service, kind, display_name, base_url, auth_scheme,
    capabilities, allowed_paths, allowed_methods, redaction_rules,
    default_risk_level, status, created_at, updated_at
FROM service_adapters
WHERE id = ?
`

func (q *Queries) GetServiceAdapterByID(ctx context.Context, id string) (ServiceAdapter, error) {
	row := q.db.QueryRowContext(ctx, getServiceAdapterByID, id)
	var i ServiceAdapter
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Kind,
		&i.DisplayName,
		&i.BaseUrl,
		&i.AuthScheme,
		&i.Capabilities,
		&i.AllowedPaths,
		&i.AllowedMethods,
		&i.RedactionRules,
		&i.DefaultRiskLevel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceAdapterByService = `-- name: GetServiceAdapterByService :one
SELECT id, service, kind, display_name, base_url, auth_scheme,
    capabilities, allowed_paths, allowed_methods, redaction_rules,
    default_risk_level, status, created_at, updated_at
FROM service_adapters
WHERE service = ?
`

func (q *Queries) GetServiceAdapterByService(ctx context.Context, service string) (ServiceAdapter, error) {
	row := q.db.QueryRowContext(ctx, getServiceAdapterByService, service)
	var i ServiceAdapter
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Kind,
		&i.DisplayName,
		&i.BaseUrl,
		&i.AuthScheme,
		&i.Capabilities,
		&i.AllowedPaths,
		&i.AllowedMethods,
		&i.RedactionRules,
		&i.DefaultRiskLevel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledServiceAdapters = `-- name: ListEnabledServiceAdapters :many
SELECT id, service, kind, display_name, base_url, auth_scheme,
    capabilities, allowed_paths, allowed_methods, redaction_rules,
    default_risk_level, status, created_at, updated_at
FROM service_adapters
WHERE status = 'enabled'
ORDER BY service
LIMIT ?
`

func (q *Queries) ListEnabledServiceAdapters(ctx context.Context, limit int64) ([]ServiceAdapter, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledServiceAdapters, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceAdapter{}
	for rows.Next() {
		var i ServiceAdapter
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.Kind,
			&i.DisplayName,
			&i.BaseUrl,
			&i.AuthScheme,
			&i.Capabilities,
			&i.AllowedPaths,
			&i.AllowedMethods,
			&i.RedactionRules,
			&i.DefaultRiskLevel,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceAdapterDeclaration = `-- name: UpdateServiceAdapterDeclaration :one
UPDATE service_adapters
SET base_url = ?, auth_scheme = ?, capabilities = ?, allowed_paths = ?,
    allowed_methods = ?, redaction_rules = ?, default_risk_level = ?, updated_at = ?
WHERE id = ?
RETURNING id, service, kind, display_name, base_url, auth_scheme,
    capabilities, allowed_paths, allowed_methods, redaction_rules,
    default_risk_level, status, created_at, updated_at
`

type UpdateServiceAdapterDeclarationParams struct {
	BaseUrl          string
	AuthScheme       string
	Capabilities     string
	AllowedPaths     string
	AllowedMethods   string
	RedactionRules   string
	DefaultRiskLevel string
	UpdatedAt        string
	ID               string
}

func (q *Queries) UpdateServiceAdapterDeclaration(ctx context.Context, arg UpdateServiceAdapterDeclarationParams) (ServiceAdapter, error) {
	row := q.db.QueryRowContext(ctx, updateServiceAdapterDeclaration,
		arg.BaseUrl,
		arg.AuthScheme,
		arg.Capabilities,
		arg.AllowedPaths,
		arg.AllowedMethods,
		arg.RedactionRules,
		arg.DefaultRiskLevel,
		arg.UpdatedAt,
		arg.ID,
	)
	var i ServiceAdapter
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Kind,
		&i.DisplayName,
		&i.BaseUrl,
		&i.AuthScheme,
		&i.Capabilities,
		&i.AllowedPaths,
		&i.AllowedMethods,
		&i.RedactionRules,
		&i.DefaultRiskLevel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateServiceAdapterStatus = `-- name: UpdateServiceAdapterStatus :one
UPDATE service_adapters
SET status = ?, updated_at = ?
WHERE id = ?
RETURNING id, service, kind, display_name, base_url, auth_scheme,
    capabilities, allowed_paths, allowed_methods, redaction_rules,
    default_risk_level, status, created_at, updated_at
`

type UpdateServiceAdapterStatusParams struct {
	Status    string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateServiceAdapterStatus(ctx context.Context, arg UpdateServiceAdapterStatusParams) (ServiceAdapter, error) {
	row := q.db.QueryRowContext(ctx, updateServiceAdapterStatus, arg.Status, arg.UpdatedAt, arg.ID)
	var i ServiceAdapter
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Kind,
		&i.DisplayName,
		&i.BaseUrl,
		&i.AuthScheme,
		&i.Capabilities,
		&i.AllowedPaths,
		&i.AllowedMethods,
		&i.RedactionRules,
		&i.DefaultRiskLevel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
