// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: settings.sql

package queries

import (
	"context"
)

const createSetting = `-- name: CreateSetting :one
INSERT INTO settings (id, name, value, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, value, created_at, updated_at
`

type CreateSettingParams struct {
	ID        string
	Name      string
	Value     string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateSetting(ctx context.Context, arg CreateSettingParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, createSetting,
		arg.ID,
		arg.Name,
		arg.Value,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings
WHERE name = ?
`

func (q *Queries) DeleteSetting(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteSetting, name)
	return err
}

const getSetting = `-- name: GetSetting :one
SELECT id, name, value, created_at, updated_at
FROM settings
WHERE name = ?
`

func (q *Queries) GetSetting(ctx context.Context, name string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, name)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT id, name, value, created_at, updated_at
FROM settings
ORDER BY name
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSettingValue = `-- name: UpdateSettingValue :one
UPDATE settings
SET value = ?, updated_at = ?
WHERE name = ?
RETURNING id, name, value, created_at, updated_at
`

type UpdateSettingValueParams struct {
	Value     string
	UpdatedAt string
	Name      string
}

func (q *Queries) UpdateSettingValue(ctx context.Context, arg UpdateSettingValueParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, updateSettingValue, arg.Value, arg.UpdatedAt, arg.Name)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
