// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: trust_memories.sql

package queries

import (
	"context"
	"database/sql"
)

const createTrustMemory = `-- name: CreateTrustMemory :one
INSERT INTO trust_memories (
    id, agent_id, workspace_id, identity_id, service,
    resource_scope, capability_scope, environment, risk_ceiling,
    approval_behavior, created_from, status, invalidation_reason,
    last_used_at, expires_at, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, agent_id, workspace_id, identity_id, service,
    resource_scope, capability_scope, environment, risk_ceiling,
    approval_behavior, created_from, status, invalidation_reason,
    last_used_at, expires_at, created_at, updated_at
`

type CreateTrustMemoryParams struct {
	ID                 string
	AgentID            string
	WorkspaceID        string
	IdentityID         string
	Service            string
	ResourceScope      string
	CapabilityScope    string
	Environment        string
	RiskCeiling        string
	ApprovalBehavior   string
	CreatedFrom        string
	Status             string
	InvalidationReason sql.NullString
	LastUsedAt         sql.NullString
	ExpiresAt          string
	CreatedAt          string
	UpdatedAt          string
}

func (q *Queries) CreateTrustMemory(ctx context.Context, arg CreateTrustMemoryParams) (TrustMemory, error) {
	row := q.db.QueryRowContext(ctx, createTrustMemory,
		arg.ID,
		arg.AgentID,
		arg.WorkspaceID,
		arg.IdentityID,
		arg.Service,
		arg.ResourceScope,
		arg.CapabilityScope,
		arg.Environment,
		arg.RiskCeiling,
		arg.ApprovalBehavior,
		arg.CreatedFrom,
		arg.Status,
		arg.InvalidationReason,
		arg.LastUsedAt,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TrustMemory
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.WorkspaceID,
		&i.IdentityID,
		&i.Service,
		&i.ResourceScope,
		&i.CapabilityScope,
		&i.Environment,
		&i.RiskCeiling,
		&i.ApprovalBehavior,
		&i.CreatedFrom,
		&i.Status,
		&i.InvalidationReason,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTrustMemory = `-- name: DeleteTrustMemory :execrows
DELETE FROM trust_memories
WHERE id = ?
`

func (q *Queries) DeleteTrustMemory(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTrustMemory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTrustMemoryByID = `-- name: GetTrustMemoryByID :one
SELECT id, agent_id, workspace_id, identity_id, service,
    resource_scope, capability_scope, environment, risk_ceiling,
    approval_behavior, created_from, status, invalidation_reason,
    last_used_at, expires_at, created_at, updated_at
FROM trust_memories
WHERE id = ?
`

func (q *Queries) GetTrustMemoryByID(ctx context.Context, id string) (TrustMemory, error) {
	row := q.db.QueryRowContext(ctx, getTrustMemoryByID, id)
	var i TrustMemory
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.WorkspaceID,
		&i.IdentityID,
		&i.Service,
		&i.ResourceScope,
		&i.CapabilityScope,
		&i.Environment,
		&i.RiskCeiling,
		&i.ApprovalBehavior,
		&i.CreatedFrom,
		&i.Status,
		&i.InvalidationReason,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const invalidateTrustMemory = `-- name: InvalidateTrustMemory :one
UPDATE trust_memories
SET status = 'invalidated', invalidation_reason = ?, updated_at = ?
WHERE id = ? AND status = 'active'
RETURNING id, agent_id, workspace_id, identity_id, service,
    resource_scope, capability_scope, environment, risk_ceiling,
    approval_behavior, created_from, status, invalidation_reason,
    last_used_at, expires_at, created_at, updated_at
`

type InvalidateTrustMemoryParams struct {
	InvalidationReason sql.NullString
	UpdatedAt          string
	ID                 string
}

func (q *Queries) InvalidateTrustMemory(ctx context.Context, arg InvalidateTrustMemoryParams) (TrustMemory, error) {
	row := q.db.QueryRowContext(ctx, invalidateTrustMemory, arg.InvalidationReason, arg.UpdatedAt, arg.ID)
	var i TrustMemory
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.WorkspaceID,
		&i.IdentityID,
		&i.Service,
		&i.ResourceScope,
		&i.CapabilityScope,
		&i.Environment,
		&i.RiskCeiling,
		&i.ApprovalBehavior,
		&i.CreatedFrom,
		&i.Status,
		&i.InvalidationReason,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTrustMemoriesByIdentity = `-- name: ListTrustMemoriesByIdentity :many
SELECT id, agent_id, workspace_id, identity_id, service,
    resource_scope, capability_scope, environment, risk_ceiling,
    approval_behavior, created_from, status, invalidation_reason,
    last_used_at, expires_at, created_at, updated_at
FROM trust_memories
WHERE identity_id = ? AND status = 'active'
ORDER BY id
LIMIT ?
`

type ListTrustMemoriesByIdentityParams struct {
	IdentityID string
	Limit      int64
}

// Feeds the cascade that invalidates an identity's memories on disconnect
// (REQ-IDENT-001 AC2).
func (q *Queries) ListTrustMemoriesByIdentity(ctx context.Context, arg ListTrustMemoriesByIdentityParams) ([]TrustMemory, error) {
	rows, err := q.db.QueryContext(ctx, listTrustMemoriesByIdentity, arg.IdentityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrustMemory{}
	for rows.Next() {
		var i TrustMemory
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.WorkspaceID,
			&i.IdentityID,
			&i.Service,
			&i.ResourceScope,
			&i.CapabilityScope,
			&i.Environment,
			&i.RiskCeiling,
			&i.ApprovalBehavior,
			&i.CreatedFrom,
			&i.Status,
			&i.InvalidationReason,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrustMemoriesByStatus = `-- name: ListTrustMemoriesByStatus :many
SELECT id, agent_id, workspace_id, identity_id, service,
    resource_scope, capability_scope, environment, risk_ceiling,
    approval_behavior, created_from, status, invalidation_reason,
    last_used_at, expires_at, created_at, updated_at
FROM trust_memories
WHERE status = ?
ORDER BY id
LIMIT ?
`

type ListTrustMemoriesByStatusParams struct {
	Status string
	Limit  int64
}

func (q *Queries) ListTrustMemoriesByStatus(ctx context.Context, arg ListTrustMemoriesByStatusParams) ([]TrustMemory, error) {
	rows, err := q.db.QueryContext(ctx, listTrustMemoriesByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrustMemory{}
	for rows.Next() {
		var i TrustMemory
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.WorkspaceID,
			&i.IdentityID,
			&i.Service,
			&i.ResourceScope,
			&i.CapabilityScope,
			&i.Environment,
			&i.RiskCeiling,
			&i.ApprovalBehavior,
			&i.CreatedFrom,
			&i.Status,
			&i.InvalidationReason,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchTrustMemories = `-- name: MatchTrustMemories :many
SELECT id, agent_id, workspace_id, identity_id, service,
    resource_scope, capability_scope, environment, risk_ceiling,
    approval_behavior, created_from, status, invalidation_reason,
    last_used_at, expires_at, created_at, updated_at
FROM trust_memories
WHERE agent_id = ? AND workspace_id = ? AND service = ? AND status = 'active'
ORDER BY id
LIMIT ?
`

type MatchTrustMemoriesParams struct {
	AgentID     string
	WorkspaceID string
	Service     string
	Limit       int64
}

func (q *Queries) MatchTrustMemories(ctx context.Context, arg MatchTrustMemoriesParams) ([]TrustMemory, error) {
	rows, err := q.db.QueryContext(ctx, matchTrustMemories,
		arg.AgentID,
		arg.WorkspaceID,
		arg.Service,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrustMemory{}
	for rows.Next() {
		var i TrustMemory
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.WorkspaceID,
			&i.IdentityID,
			&i.Service,
			&i.ResourceScope,
			&i.CapabilityScope,
			&i.Environment,
			&i.RiskCeiling,
			&i.ApprovalBehavior,
			&i.CreatedFrom,
			&i.Status,
			&i.InvalidationReason,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tightenTrustMemoryBehavior = `-- name: TightenTrustMemoryBehavior :one
UPDATE trust_memories
SET approval_behavior = 'always_ask', updated_at = ?
WHERE id = ? AND status = 'active' AND approval_behavior = 'auto_allow'
RETURNING id, agent_id, workspace_id, identity_id, service,
    resource_scope, capability_scope, environment, risk_ceiling,
    approval_behavior, created_from, status, invalidation_reason,
    last_used_at, expires_at, created_at, updated_at
`

type TightenTrustMemoryBehaviorParams struct {
	UpdatedAt string
	ID        string
}

// Only auto_allow -> always_ask (REQ-TRUST-005). The direction is pinned in the
// WHERE clause, so widening cannot be expressed here at all.
func (q *Queries) TightenTrustMemoryBehavior(ctx context.Context, arg TightenTrustMemoryBehaviorParams) (TrustMemory, error) {
	row := q.db.QueryRowContext(ctx, tightenTrustMemoryBehavior, arg.UpdatedAt, arg.ID)
	var i TrustMemory
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.WorkspaceID,
		&i.IdentityID,
		&i.Service,
		&i.ResourceScope,
		&i.CapabilityScope,
		&i.Environment,
		&i.RiskCeiling,
		&i.ApprovalBehavior,
		&i.CreatedFrom,
		&i.Status,
		&i.InvalidationReason,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchTrustMemory = `-- name: TouchTrustMemory :one
UPDATE trust_memories
SET last_used_at = ?, updated_at = ?
WHERE id = ? AND status = 'active'
RETURNING id, agent_id, workspace_id, identity_id, service,
    resource_scope, capability_scope, environment, risk_ceiling,
    approval_behavior, created_from, status, invalidation_reason,
    last_used_at, expires_at, created_at, updated_at
`

type TouchTrustMemoryParams struct {
	LastUsedAt sql.NullString
	UpdatedAt  string
	ID         string
}

func (q *Queries) TouchTrustMemory(ctx context.Context, arg TouchTrustMemoryParams) (TrustMemory, error) {
	row := q.db.QueryRowContext(ctx, touchTrustMemory, arg.LastUsedAt, arg.UpdatedAt, arg.ID)
	var i TrustMemory
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.WorkspaceID,
		&i.IdentityID,
		&i.Service,
		&i.ResourceScope,
		&i.CapabilityScope,
		&i.Environment,
		&i.RiskCeiling,
		&i.ApprovalBehavior,
		&i.CreatedFrom,
		&i.Status,
		&i.InvalidationReason,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
