// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workspaces.sql

package queries

import (
	"context"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, path, project_fingerprint, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, path, project_fingerprint, created_at, updated_at
`

type CreateWorkspaceParams struct {
	ID                 string
	Path               string
	ProjectFingerprint string
	CreatedAt          string
	UpdatedAt          string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace,
		arg.ID,
		arg.Path,
		arg.ProjectFingerprint,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.ProjectFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, path, project_fingerprint, created_at, updated_at
FROM workspaces
WHERE id = ?
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.ProjectFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByPath = `-- name: GetWorkspaceByPath :one
SELECT id, path, project_fingerprint, created_at, updated_at
FROM workspaces
WHERE path = ?
`

func (q *Queries) GetWorkspaceByPath(ctx context.Context, path string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByPath, path)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.ProjectFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspaceFingerprint = `-- name: UpdateWorkspaceFingerprint :one
UPDATE workspaces
SET project_fingerprint = ?, updated_at = ?
WHERE id = ?
RETURNING id, path, project_fingerprint, created_at, updated_at
`

type UpdateWorkspaceFingerprintParams struct {
	ProjectFingerprint string
	UpdatedAt          string
	ID                 string
}

func (q *Queries) UpdateWorkspaceFingerprint(ctx context.Context, arg UpdateWorkspaceFingerprintParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, updateWorkspaceFingerprint, arg.ProjectFingerprint, arg.UpdatedAt, arg.ID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.ProjectFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
